project:
  type: book
  output-dir: docs
book:
  title: "BWAM Analytics"
  author: "Zachary M. Smith"
  date: "6/24/2024"
  reader-mode: true
  repo-url: https://github.com/BWAM/bwam_analytics
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd

    - wqma_oracle_db.qmd

    - analytical_data_store.qmd

    - generate_parquet_files.qmd

    - data_dictionary.qmd

    - wqx_api.qmd

    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-link: true

editor: visual

