---
title: "Data Dictionary"
author: "Zachary M. Smith"
---

The data dictionary below describes data from the WQMA Oracle database and the WQMA Analytical Data Store (WQMA parquet files).

::: callout-important
The data dictionary empowers data users to quickly become familiar with a data set. Although the table is simple, it is critical to operations that this table remain up-to-date, accurate, and easy to understand.

If you find any errors or do not find the documentation clear, please open a [GitHub Issue](https://github.com/BWAM/bwam_analytics/issues) and we can collectively work towards a solution.
:::

The dictionary provides:

1.  [**table_name:**]{.underline} The name of the table in the WQMA Oracle Database where the **column_name** is stored.

2.  [**column_name:**]{.underline} The name of the column in the data store of interest. The naming convention is the same between the WQMA Oracle Database and WQMA Analytical Data Store.

3.  [**examples:**]{.underline} Provides examples of the data found in a column. If more than 20 unique values are represented in the column, then 20 example character strings will be provided. If 20 or less unique values are represented in the column, all 20 values are provided.

4.  [**definition:**]{.underline} A description of what the column represents.

5.  [**db_data_type:**]{.underline} The columns data type in the Oracle Database.

6.  [**character_limit:**]{.underline} If present, the numeric value represents the maximum character string length that is allowed in VARCHAR or character column of the Oracle database.

7.  [**not_null:**]{.underline} Indicates if the column can (FALSE) or cannot (TRUE) contain *NULL* or *NA* values.

8.  [**surrogate_key:**]{.underline} Indicates if a column represents a unique sequential number ID generated by the Oracle database (TRUE) or a value provided by the program (FALSE).

9.  [**primary_key:**]{.underline} Indicates if a column represents the unique identifier for a table (TRUE) or not (FALSE). Multiple columns can be listed as primary keys, which together form a composite key that uniquely identifies a row in the table.

10. [**foreign_key:**]{.underline} Indicates if a column has a relationship to another table (TRUE) or not (FALSE). There can be multiple columns in a single table that act as foreign keys to a single table. There can be multiple foreign key relationships, but a single column should only relate to a single **parent_table**.

11. [**parent_table:**]{.underline} Provides the name of the table that a foreign key column relates to.

```{r, echo=FALSE}
library(DT)
data("columns_dictionary",
     package = "nexus")

DT::datatable(
  columns_dictionary,
  filter = 'top',
  extensions = c('Buttons',
                 'FixedHeader'),
  options = list(pageLength = 50,
                 autoWidth = TRUE,
                 fixedHeader = TRUE,
                 dom = 'Bfrtip',
                 buttons = c('copy',
                             'csv',
                             'excel',
                             'pdf',
                             'print'))
)

```
